name: test on pull request

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install boost
      run: sudo apt update && sudo apt install libboost-test-dev libomp-dev
    - name: make
      run: make
    - name: test
      run: ./test.o
